import ApprovedCaseStudy from "@/pages/ApprovedCaseStudy";

export const RealTimeEngagement = () => <ApprovedCaseStudy study={{ title: "Real-time player value", label: "An iGaming operator", subtitle: "Helping teams act while the player is still active", problem: ["The team often acted after a player’s session had ended. By that point, the player could already have left the platform, missed a relevant offer, or had a poor experience.", "The aim was to help the business spot the right moment during a live session, so it could take better action while the player was still active."], work: ["The work covered the full path from data to action: understanding player behaviour and the business question; building and testing an engagement model; giving CRM, Product, and Data teams a clear view of the signals; and supporting live use of the result in the business."], changed: "The work helped teams use real-time player signals to improve engagement and target more relevant offers during an active session.", result: "Average customer lifetime value increased by 3%.", cta: "Could your team act at the right moment?", ctaText: "Book a 20-minute AI readiness call to explore whether your customer and operational data can support a practical AI decision." }} />;

export const DentalReception = () => <ApprovedCaseStudy study={{ title: "Smarter dental reception", label: "A dental clinic", subtitle: "Live AI support for patient questions and bookings", problem: ["The reception team had a high workload. Patients also needed faster help with common questions and booking requests.", "The clinic needed a way to improve support without adding more repeated manual work for the reception team."], work: ["A live voice AI agent was built to answer common patient questions and help with booking requests.", "It supported the reception team by handling repeated work, so staff could spend more time on higher-value patient support."], changed: "Patients could get faster help with questions and bookings. The reception team had less repeated manual work and more time for work that needed a person.", result: "The live system showed potential to save up to 1,000 receptionist hours each year.", cta: "Could AI take repeated work off your team’s plate?", ctaText: "Book a 20-minute AI readiness call to explore where AI could improve your customer or operations workflows." }} />;

export const IncidentSupport = () => <ApprovedCaseStudy study={{ title: "Smarter incident support", label: "An IT service provider", subtitle: "Live AI help for hard incidents", problem: ["The service team had a high workload. Junior staff often needed senior engineers to help solve hard incidents.", "The business needed a way to help more people handle difficult incidents without depending on senior staff for every case."], work: ["A live AI platform was built to find useful knowledge and give staff clear guidance while they handled hard incidents.", "It helped junior staff work through difficult cases and reduced the need for senior engineers to be involved in every incident."], changed: "The team could find the right information faster and take clearer next steps during hard incidents.", result: "93% successful resolution of hard incidents in tested cases reviewed by subject experts.", cta: "Could your team resolve hard work with clearer support?", ctaText: "Book a 20-minute AI readiness call to explore where AI could help your service or operations team make better decisions." }} />;

export const DocumentsToData = () => <ApprovedCaseStudy study={{ title: "From documents to data", label: "A healthcare information provider", subtitle: "Live AI support for agreement data", problem: ["The team had to read healthcare agreements and copy key information into other systems by hand. This was slow, error-prone and hard to scale.", "The business needed a better way to turn agreement information into clear, usable data."], work: ["A live AI agent was built to extract key information from agreements and create structured data.", "It reduced repeated manual work and helped the business rely less on specialist analysts for every case."], changed: "The team could process agreement information faster, with better accuracy and a more scalable way of working.", result: "Faster processing, better accuracy and less reliance on specialist analysts.", cta: "Could AI turn your documents into useful data?", ctaText: "Book a 20-minute AI readiness call to explore where AI could improve your customer or operations workflows." }} />;
