import { useEffect } from "react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

type CaseStudy = { title: string; label: string; subtitle: string; problem: string[]; work: string[]; changed: string; result?: string; cta: string; ctaText: string };

export default function ApprovedCaseStudy({ study }: { study: CaseStudy }) {
  useEffect(() => { document.title = `${study.title} | Traviz`; }, [study.title]);
  return <div className="min-h-screen bg-off-white"><Navigation /><main className="pt-16"><section className="bg-charcoal py-20 text-white"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><p className="mb-4 text-sm font-semibold uppercase tracking-wider text-electric-teal">{study.label}</p><h1 className="mb-6 text-4xl font-bold leading-tight sm:text-5xl">{study.title}</h1><p className="text-lg text-gray-200">{study.subtitle}</p></div></section><article className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8"><section className="mb-14"><h2 className="mb-5 text-3xl font-bold text-charcoal">The problem</h2><div className="space-y-5 text-lg leading-relaxed text-muted-blue">{study.problem.map(text => <p key={text}>{text}</p>)}</div></section><section className="mb-14"><h2 className="mb-5 text-3xl font-bold text-charcoal">The work</h2><div className="space-y-5 text-lg leading-relaxed text-muted-blue">{study.work.map(text => <p key={text}>{text}</p>)}</div></section><section className="mb-14"><h2 className="mb-5 text-3xl font-bold text-charcoal">What changed</h2><p className="text-lg leading-relaxed text-muted-blue">{study.changed}</p></section>{study.result && <section className="mb-14 rounded-xl bg-soft-lilac p-8"><h2 className="mb-3 text-3xl font-bold text-charcoal">Result</h2><p className="text-lg font-semibold leading-relaxed text-muted-blue">{study.result}</p></section>}<section className="rounded-2xl bg-soft-lilac p-8 text-center sm:p-12"><h2 className="mb-4 text-3xl font-bold text-charcoal">{study.cta}</h2><p className="mx-auto mb-8 max-w-2xl text-lg leading-relaxed text-muted-blue">{study.ctaText}</p><a href="/#contact" className="inline-flex rounded-lg bg-logo-purple px-6 py-3 font-semibold text-white transition-opacity hover:opacity-90">Book a 20-minute AI readiness call</a></section></article></main><Footer /></div>;
}
