import { Link } from "wouter";
import { ArrowRight, BarChart3 } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

const studies = [
  ["An anonymised European sportsbook operator", "From churn ambiguity to a route for earlier retention action", "Churn prediction", "Retention decisions relied on retrospective signals and rule-based targeting, while data quality made it difficult to define an earlier operational churn signal.", "/case-studies/sportsbook-churn-prediction"],
  ["An iGaming operator", "Real-time player value", "Helping teams use live player signals to improve engagement and target more relevant offers.", "Average customer lifetime value increased by 3%.", "/case-studies/real-time-engagement"],
  ["A dental clinic", "Smarter dental reception", "A live AI agent answered patient questions and helped with bookings, reducing repeated work for the reception team.", "Showed potential to save up to 1,000 receptionist hours each year.", "/case-studies/dental-ai-receptionist"],
  ["An IT service provider", "Smarter incident support", "A live AI platform found useful knowledge and guided staff through hard incidents.", "93% successful resolution of hard incidents in tested cases reviewed by subject experts.", "/case-studies/ai-incident-resolution"],
  ["A healthcare information provider", "From documents to data", "A live AI agent extracted key agreement information and created structured data, reducing manual work for analysts.", "Faster processing, better accuracy and less reliance on specialist analysts.", "/case-studies/healthcare-agreement-ai"],
];

export default function CaseStudies() { return <div className="bg-cool-gray py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12 text-center"><h2 className="mb-4 text-4xl font-bold text-charcoal">Case studies</h2></div><div className="grid gap-6 lg:grid-cols-2">{studies.map(([label, title, text, result, href]) => <Card key={href} className="bg-white shadow-lg"><CardContent className="p-8"><div className="mb-5 flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-logo-purple"><BarChart3 className="h-6 w-6 text-white" /></div><div><p className="mb-2 text-sm font-semibold uppercase tracking-wider text-muted-blue">{label}</p><h3 className="text-2xl font-bold text-charcoal">{title}</h3></div></div><p className="mb-5 leading-relaxed text-muted-blue">{text}</p><p className="font-semibold leading-relaxed text-charcoal">{result}</p><Link href={href} className="mt-7 inline-flex items-center gap-2 font-semibold text-logo-purple transition-opacity hover:opacity-75">Read the case study <ArrowRight className="h-4 w-4" /></Link></CardContent></Card>)}</div></div></div>; }
